### ISSUE TITLE
Week 8 - Use of .loc[]

### ISSUE THREAD

**Issue by simonperrault** [Data-Driven-World/d2w_notes#10]
```The code above prints the column resale_price and its type. As can be seen the type of the output is a Series data type.

You can also get some particular row by specifying its index.

You can also access the column using the .loc[index, column] method. In this method, you need to specify the labels of the index.
```

You do explain that we can use : at some point.
I would mention it here, and also mention that a particular column can be addressed by using its name, but that one can select all columns also by using : 
Finally, it may be good to remind them of where this : comes from (lists)

**Comment by kurniawano** [comment]
@simonperrault thanks, I have tried to include some of your suggestions in the notes.
