### ISSUE TITLE
Remind students about abstraction

### ISSUE THREAD

**Issue by otakuprof** [Data-Driven-World/d2w_notes#16]
Students could be reminded of abstraction at the start of the OOP section.

**Comment by kurniawano** [comment]
@otakuprof , Norman, any suggestion on where we should include this in the note?

**Comment by otakuprof** [comment]
> @otakuprof , Norman, any suggestion on where we should include this in the note?

At the start of the OOP section.

**Comment by kurniawano** [comment]
@otakuprof , thanks, I put some notes in the commit above. Let me know if that sounds ok.
