### ISSUE TITLE
Help students to recall pure functions. 

### ISSUE THREAD

**Issue by otakuprof** [Data-Driven-World/d2w_notes#17]
in the state_machine_abc.ipynb: 
=======

In the above implementation, we also define start() method as simply applying the start_state as the current state value of the machine. Moreover, the step(inp) calls get_next_values(state, inp), which should be implemented in the child class, to get the next state and the output given the current state and the current input. The next state is then applied to the state and the step() method returns the output. 

<p style="color:DodgerBlue;">Thus, step() is designed to update the state of the state machine. Thus, when get_next_values() is implemented, it must be implemented as a pure function. </p>

**Creating a LightBoxSM Class**

**Comment by kurniawano** [comment]
Thanks @otakuprof , I have added the last sentence.
