### ISSUE TITLE
Typo in ComputationTime

### ISSUE THREAD

**Issue by iangohy** [Data-Driven-World/d2w_notes#19]
# Measuring Computation Time > Setup.

## Typo
We generate the input array of integers with different number of elements from 10 up to 10,000, i.e. 10 ~~elments~~ elements, 100 elements, 1000 elements, and 10,000 elements.

**Comment by iangohy** [comment]
Another typo under `Bubble Sort Computation Time > version 4 computation time`. 

## Typo
In the ~~wors't~~ worst case, the number of swap will be the same as $n-1$.

**Comment by kurniawano** [comment]
Thanks @iangohy .
