### ISSUE TITLE
Complexity Notes Typo near In[40]

### ISSUE THREAD

**Issue by natalieagus** [Data-Driven-World/d2w_notes#21]
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/5848920/134119495-dd7e3996-c312-4d7e-9629-3f164d1f50c9.png">

There's a typo in the slope computation, it should be 1 instead of 0.5 :)

**Comment by kurniawano** [comment]
@natalieagus , which part is this? Is this on the heapsort? The heapsort slope should be less than 2 because the plot is log(y). If it is 2, then it is quadratic. So it should be less than 2.
```
log(x^2) = 2 * log(x)
```

**Comment by natalieagus** [comment]
Oh i meant just by solving the formula, if the formula is correct that:
-4 - (-8) = 4, 12-8 = 4, so it should be 1? Sorry I have a typo also and type 2...

**Comment by kurniawano** [comment]
Ah right, Will fix it. Thanks.
