### ISSUE TITLE
Clarification and Typo in Merge_Sort.ipynb

### ISSUE THREAD

**Issue by iangohy** [Data-Driven-World/d2w_notes#24]
## Clarification
Can I clarify what is meant by 
![image](https://user-images.githubusercontent.com/16506822/134459468-ca966ccf-2588-4aba-9eb8-ea4fcdd3f160.png)
```
At the bottom of the tree, we can only $c\times 1$, and so
```
Sounds like it was typed halfway hmm.

### 1
And if we sum up the computation time at each ~leve~ level, we would obtain $c\times n$. For example at level $i = 1$, we have

### 2
and similarly at ~everly~ every level. Therefore, the total computation time is the sum at each level multiplied by the number of level.

**Comment by kurniawano** [comment]
Thanks @iangohy . Regarding the sentence, yeah I have rephrased it. There is nothing after that.
