### ISSUE TITLE
Difference between a 'state' and an 'output'? (State Machine)

### ISSUE THREAD

**Issue by Jiang-Wenchao** [Data-Driven-World/d2w_notes#41]
Hi @luzhuomi and @kurniawano ,

Thanks for your previous answer about the pure function and the state machine. It's more clear to me now. The AND function is a pure function because the output can be derived from its inputs. In my understanding, the gap between a state machine and a pure function is not whether you are using the history input, but whether the history input is considered visible to the users. If the history input is all passed in as arguments, it is a pure function. If the history input is stored in the property hidden from the users, it is a state machine.

I have another question about the 'state' and 'output' in the section 'Next State Function'. I agree with the description that a state is not necessarily the output. But my question is when you design such a transition diagram, how do you define the 'state' and 'output'? For example, in the coke machine example, the first output is 'the amount of money inside the machine'. Why can't I use 'the amount of money in the machine' as the state? Also the second output y is 'the status whether coke is dispensed or not', why can't that be a state? I am wondering is there any rule of thumb when we are plotting the transition diagram? Thanks.

**Comment by luzhuomi** [comment]
Hi @Jiang-Wenchao 

Regarding your second question, yes, I believe that we can use the balance as the state instead of 0 and 1, because 0 implies balance = 0, 1 implies balance = 50.  With regards to use whether a coke has been dispensed or not, it seems to work if we look at the diagram. However 1) it is unnatural to use last performed action as a state. 2) there is a hidden transition only captured in the code but not in the diagram, i.e. if the inp is not 50 nor 100, the machine does not change its state, nor does it dispense a coke. 

That's what I am guessing. Maybe @kurniawano  can share his view on this.

**Comment by kurniawano** [comment]
@Jiang-Wenchao , thanks for the discussion. You are absolutely right that there is no one single state machine design solutions. I guess this is where design comes in. There can be many state machine design for a given coke machine. We just somehow chose this "particular" design for the coke machine. For example, it is true that the state in our note in a way represent whether there is a money inside the machine or not. 

There are two State Machine machines, Mealy and Moore. In this course, we teach Mealy machine where the state is different from the output (though it can be the same as you indicated about the money inside the machine). In Moore machine, on the other hand, the output is determined by the current state so the state somehow always represents the output. Now, it has been proven that these two representations (Mealy and Moore) are equivalent. You can always convert from one to the other.

**Comment by Jiang-Wenchao** [comment]
Thanks to @luzhuomi and @kurniawano for sharing your viewpoints.  Maybe we can explain the transition diagram as one example, not the only one, to avoid arguments. And I also read about the Moore and Mealy state machines. Thanks for the clarification.

**Comment by kurniawano** [comment]
@Jiang-Wenchao , thanks. I have added the clarification in the latest commit.
