### ISSUE TITLE
Note regarding binary heap

### ISSUE THREAD

**Issue by luzhuomi** [Data-Driven-World/d2w_notes#50]
Currently it is written as follows in the note
"
The heap is an array of object that we can view as a nearly complete binary tree. 
"
But binary heaps are actually complete binary trees.  If we would like to use the word "nearly", it would be nearly perfect binary tree.
A perfect binary tree is a full binary tree which all leaf nodes are at the same level. Binary heaps (complete trees), are nearly perfect except the last level and all the leaves at the last level are packed towards the left.

May it makes more sense to introduce perfect binary trees first then complete binary trees.

**Comment by natalieagus** [comment]
thanks. fixed this in the site repo, see: https://github.com/Data-Driven-World/Data-Driven-World.github.io/commit/292d49817361e1bfaff49a0efc9a7e1417a38868
