### ISSUE TITLE
Missing image in intro_graph?

### ISSUE THREAD

**Issue by luzhuomi** [Data-Driven-World/d2w_notes#51]
In the intro_graph note,

"""
The above UML diagram shows that a Graph is composed of one or more Vertex objects. This is another composition relationship between two classes.

We can specify the attributes and methods for both classes as shown in the image below.
"""

But there is no image below. Is it missing?

**Comment by kurniawano** [comment]
@luzhuomi , fixed in Data-Driven-World/Data-Driven-World.github.io@87a0f6ee4ae6f9831189b3db3f5c71062b752f49 .
