### ISSUE TITLE
Consider a simpler example for Divide-And-Conquer

### ISSUE THREAD

**Issue by otakuprof** [Data-Driven-World/d2w_notes#9]
Currently, the divide-and-conquer begins by using summing of an array to illustrate the ideas. 

We could start by illustrating how a recursive version of a factorial can be derived. This will be more familiar to students. 

https://github.com/Data-Driven-World/d2w_notes/blob/master/Divide_Conquer.ipynb

**Comment by kurniawano** [comment]
@otakuprof , thanks Norman. I did put factorial example after the summation example since I thought factorial is more complicated as compared to summing. I'll consider this. In the mean time, I will close the issue first.
